FROM php:8.2-fpm

# Installer les dépendances nécessaires pour PHP et Composer
RUN apt-get update && apt-get install -y \
    zip \
    libzip-dev \
    unzip \
    git \
    curl \
    && docker-php-ext-install zip

# Installer Composer
COPY --from=composer:2.6 /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail
WORKDIR /var/www/html

# Copier les fichiers de l'application dans le conteneur
COPY . .

# Installer les dépendances PHP via Composer (si composer.json existe)
RUN composer install --no-dev --optimize-autoloader --ignore-platform-reqs

EXPOSE 8000

CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
