services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8081:80'
    volumes:
    - ./:/var/www/html
    - ../apache.conf:/etc/apache2/sites-available/000-default.conf


  php:
    image: php:latest
    container_name: my-php-app
    ports:
      - '9000:9000'
